name: Slack Notification

inputs:
  pr_link:
    description: 'Pull request link to send to Slack'
    required: true
    type: string
  webhook_url:
    description: 'Webhook URL to send the message to'
    required: true
    type: string

  previous_version:
    description: 'Previous version to send to Slack'
    required: true
    type: string
  new_version:
    description: 'New version to send to Slack'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - uses: slackapi/slack-github-action@v2.1.1
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
      with:
        webhook-type: incoming-webhook
        payload: |
          {
            "pr_link": "${{ inputs.pr_link }}",
            "previous_version": "${{ inputs.previous_version }}",
            "new_version": "${{ inputs.new_version }}"
          }
