name: Slack Notification

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to send to Slack'
        required: true
        type: string

jobs:
  slack_notification:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v2.1.1
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
                "TEXT": "${{ inputs.message }}"
            }
